export type Align = "center" | "left" | "right";

export interface Position {
  x: number; // Prozent (0–100)
  y: number; // Prozent (0–100)
}

export interface PosterSize {
  label: string;
  w: number;
  h: number;
}

export interface PatternConfig {
  patternType: "lines" | "wavy" | "grid";
  count: number;       // 1–20 strokes
  brushName: string;   // svg-brush name, e.g. "Figma Verite"
  strokeWidth: number; // 0.3–4.0 (multiplier)
  opacity: number;     // 10–100 %
  color: "white" | "black";
  seed: number;
}

/** SVG-based background stroke (generated by svg-brush). */
export interface PatternStroke {
  id: string;
  svgPath: string;  // SVG path `d` attribute from createBrushStroke
  opacity: number;  // 0–1
  offsetX: number;  // % offset from drag
  offsetY: number;
}

/** Werkzeug-Modus: Elemente verschieben vs. Freihand zeichnen. */
export type ToolMode = "move" | "draw";

/** SVG-based freehand chalk stroke (drawn by the user). */
export interface ChalkStroke {
  id: string;
  svgPath: string;     // SVG path `d` attribute from createBrushStroke
  color: string;
  opacity: number;     // 0–1
  offsetX: number;     // % offset from drag
  offsetY: number;
  zIndex: number;
  isGenerated: boolean;
}

export type AssetCategory =
  | "portraits"
  | "buildings"
  | "icons"
  | "ornaments"
  | "logos"
  | "shapes" // Formen: gerissenes Papier & Linien/Trenner (weiß-auf-transparent SVG, tintbar)
  | "strokes"; // Echte Kreide-Stroke-Stamps (weiß-auf-transparent PNG)

export interface AssetItem {
  id: string;
  name: string;
  category: AssetCategory;
  src: string; // Import-Pfad (URL)
  defaultScale: number; // Empfohlene Startgröße (0.1–1.0 relativ zum Poster)
  anchor: "center" | "top" | "bottom" | "corner"; // Für Smart Placement
  naturalWidth?: number; // Nur Stroke-Stamps: Originalmaße fürs Seitenverhältnis
  naturalHeight?: number;
  // Nur hochgeladene Fotos: Original-URL (für erneutes Kreide-Verarbeiten) und
  // die aktuell angewandten Kreide-Filter-Parameter. `src` zeigt dann auf die
  // verarbeitete Data-URL (bzw. = originalSrc, wenn der Filter aus ist).
  originalSrc?: string;
  chalk?: ChalkAssetSettings;
}

/** Kreide-Filter-Einstellungen eines hochgeladenen Fotos. */
export interface ChalkAssetSettings {
  enabled: boolean; // Filter an/aus (aus = Originalfoto)
  contrast: number; // 0.5–2.5
  brightness: number; // -0.3–0.3
  threshold: number; // 0 = weiche Schattierung, >0 = harter Cutout
}

export interface PlacedAsset {
  id: string; // Unique ID
  assetId: string; // Referenz auf AssetItem
  x: number; // Position in % (0–100)
  y: number; // Position in % (0–100)
  scale: number; // Skalierung / Länge (0.05–2.0)
  rotation: number; // Grad (0–360)
  opacity: number; // 0–1
  flipX: boolean; // Horizontal spiegeln
  zIndex: number; // Ebene
  // Freies Stretchen (per Maus-Griffe): horizontaler/vertikaler Streckfaktor
  // zusätzlich zur Basis-Größe `scale` (Default je 1).
  scaleX?: number; // Horizontaler Streckfaktor (Default 1)
  scaleY?: number; // Vertikaler Streckfaktor / Strichstärke (Default 1)
  flipY?: boolean; // Vertikal spiegeln
  tint?: string; // Kreide-Farbe (Hex); leer = weiß
}

